services:
    app.locale_listener:
        class: Kimerikal\UtilBundle\EventListener\LocaleListener
        arguments: [@router, "%kernel.default_locale%"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_subscriber }
    ajax_select:
        class: Kimerikal\UtilBundle\Form\Type\AjaxSelectType
        arguments:
            - '@router'
        tags:
            -  { name: form.type }