services:
    app.locale_listener:
        class: Kimerikal\UtilBundle\EventListener\LocaleListener
        arguments: [@router, "%kernel.default_locale%"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_subscriber }
    ajax_select:
        class: Kimerikal\UtilBundle\Form\Type\AjaxSelectType
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'
        tags:
            -  { name: form.type }
    entity_ajax_select:
        class: Kimerikal\UtilBundle\Form\Type\EntityAjaxSelectType
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'
        tags:
            -  { name: form.type }
            
    json_array:
        class: Kimerikal\UtilBundle\Form\Type\JSONArrayType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            -  { name: form.type }
            
    tree_select:
        class: Kimerikal\UtilBundle\Form\Type\TreeSelectType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            -  { name: form.type }

    k_service.google_maps:
        class: Kimerikal\UtilBundle\Service\KGoogleMaps
        arguments: ['%app.google_api_key%']

    k_service.firebase_notifications:
        class: Kimerikal\UtilBundle\Service\KFireBaseNotifications
        arguments: ['%app.firebase_messages_server_key%', "@doctrine.orm.entity_manager"]

    k_service.email_notifications:
        class: Kimerikal\UtilBundle\Service\KEmailNotifications
        arguments: ["@twig", "@mailer", "%app.title%", "%mailer_user%"]

    k_service.form.type.color:
        class: Kimerikal\UtilBundle\Form\Type\ColorType
        tags:
            - {name: form.type, alias: color}

    k_service.form.type.quill:
        class: Kimerikal\UtilBundle\Form\Type\QuillType
        tags:
            - { name: form.type, alias: quill }

