services:
    app.locale_listener:
        class: OfCoding\UtilBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }