services:
    app.locale_listener:
        class: Kimerikal\UtilBundle\EventListener\LocaleListener
        arguments: [@router, "%kernel.default_locale%"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_subscriber }
    ajax_select:
        class: Kimerikal\UtilBundle\Form\Type\AjaxSelectType
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'
        tags:
            -  { name: form.type }
            
    json_array:
        class: Kimerikal\UtilBundle\Form\Type\JSONArrayType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            -  { name: form.type }